apiVersion: v2
description: A Helm chart for Hearing Recording Service
name: em-hrs-api
home: https://github.com/hmcts/em-hrs-api
version: 1.0.5
maintainers:
  - name: HMCTS Evidence Management team
dependencies:
  - name: java
    version: 3.7.7
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: blobstorage
    version: 0.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled
