apiVersion: v2
description: A Helm chart for Hearing Recording Service
name: em-hrs-api
home: https://github.com/hmcts/em-hrs-api
version: 1.0.12
maintainers:
  - name: HMCTS Evidence Management team
dependencies:
  - name: java
    version: 4.0.12
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: blobstorage
    version: 0.3.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled
