apiVersion: v2
description: A Helm chart for Hearing Recording Service
name: em-hrs-api
home: https://github.com/hmcts/em-hrs-api
version: 1.1.1
maintainers:
  - name: HMCTS Evidence Management team
dependencies:
  - name: java
    version: 4.1.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: blobstorage
    alias: hrsblobstorage
    version: 0.3.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: hrsblobstorage.enabled
  - name: blobstorage
    alias: cvpblobstorage
    version: 0.3.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: cvpblobstorage.enabled
