java:
  postgresql:
    postgresqlUsername: emhrs
    postgresqlPassword: emhrs
    nameOverride: em-hrs-db
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/em/hrs-api:latest'
  ingressHost: em-hrs-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: em
  keyVaults:
    em-hrs-api:
      resourceGroup: em-hrs-api
      secrets:
        - hrs-api-POSTGRES-PASS
        - microservicekey-em-hrs-api
        - storage-account-primary-connection-string
  environment:
    # db
    SPRING_DATASOURCE_URL: jdbc:postgresql://em-hrs-api-postgres-v11-db-{{ .Values.global.environment }}.postgres.database.azure.com:5432/emhrs?ssl=disable
    SPRING_DATASOURCE_USERNAME: emhrs@em-hrs-api-postgres-v11-db-{{ .Values.global.environment }}

    # Document Storage
    STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME: em-hrs-api-{{ .Values.global.environment }}

    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    OIDC_ISSUER_BASE_URI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    IDAM_API_BASE_URI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

blobstorage:
  resourceGroup: em-hrs-api-aks
  teamName: "EM"
  location: uksouth
  setup:
    containers:
      - em-hrs-api
  enabled: false
