java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  readinessDelay: 45
  keyVaults:
    em-hrs-api:
      resourceGroup: em-hrs-api
      secrets:
        - storage-account-primary-connection-string
        - idam-system-user-name
        - idam-system-user-password
        - hrs-api-POSTGRES-PASS
        - microservicekey-em-hrs-api
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/javadatabase?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
    ENABLE_LIQUIBASE: true
    ENABLE_DB_MIGRATE: true
    STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=$(BLOB_ACCOUNT_NAME);AccountKey=$(BLOB_ACCESS_KEY);EndpointSuffix=core.windows.net"
    CVP_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=$(BLOB_ACCOUNT_NAME);AccountKey=$(BLOB_ACCESS_KEY);EndpointSuffix=core.windows.net"
  postgresql:
    enabled: true
blobstorage:
  enabled: true
  resourceGroup: em-hrs-api-aks
  teamName: "EM"
  location: uksouth
  setup:
    containers:
      - em-hrs-api

