# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    em-hrs-api:
      secrets:
        - name: hrs-api-POSTGRES-PASS
          alias: SPRING_DATASOURCE_PASSWORD
        - name: microservicekey-em-hrs-api
          alias: S2S_KEY
        - name: storage-account-primary-connection-string
          alias: STORAGEACCOUNT_PRIMARY_CONNECTION_STRING
        - name: cvp-storage-connection-string
          alias: CVP_STORAGE_CONNECTION_STRING
        - name: cvp-storage-container-name
          alias: CVP_STORAGE_CONTAINER_NAME
        - name: vh-storage-connection-string
          alias: VH_STORAGE_CONNECTION_STRING
        - name: vh-storage-container-name
          alias: VH_STORAGE_CONTAINER_NAME
        - name: hrs-storage-container-name
          alias: HRS_CVP_DEST_CONTAINER_NAME
        - name: idam-system-user-name
          alias: HRS_SYSTEM_USER
        - name: idam-system-user-password
          alias: HRS_SYSTEM_USER_PASSWORD
        - name: notification-api-key-pretend-to-send
          alias: NOTIFICATION_API_KEY
        - name: hrs-reports-email-username
          alias: SMTP_USERNAME
        - name: hrs-reports-email-password
          alias: SMTP_PASSWORD
        - name: summary-report-recipients
          alias: SUMMARY_REPORT_RECIPIENTS
        - name: monthly-hearing-report-recipients
          alias: MONTHLY_HEARING_REPORT_RECIPIENTS
        - name: report-api-key
          alias: REPORT_API_KEY

ccd:
  enabled: true
  ccd:
    adminWeb:
      enabled: false
    apiGatewayWeb:
      enabled: true
    definitionImporter:
      enabled: false
    managementWeb:
      enabled: false
    s2s:
      enabled: false
    postgresql:
      enabled: false
    ras:
      enabled: false
    userProfileImporter:
      enabled: false
    userProfile:
      enabled: false
  global:
    ccdApiGatewayIngress: http://${SERVICE_NAME}-ccd-api-gw
    ccdDataStoreUrl: http://${SERVICE_NAME}-ccd-data-store-api
    ccdStitchUrl: http://${SERVICE_NAME}-emstitch
    ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store
    ccdUserProfileUrl: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    postgresSecret: postgres

  ccd-api-gateway-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_SECRET}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}
      keyVaults: []
  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      devcpuRequests: 500m
      devmemoryRequests: 4096Mi
      devmemoryLimits: 8192Mi
      autoscaling:
        enabled: false
      environment:
        CASE_DOCUMENT_AM_API_ATTACH_DOCUMENT_ENABLED: true
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${CCD_DATA_STORE_S2S_SECRET}
        DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
        DATA_STORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,civil_service,ccd_case_document_am_api,aac_manage_case_assignment
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment
        CASE_DOCUMENT_AM_URL: http://${SERVICE_NAME}-cdam
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        CCD_MULTIPARTY_FIX_ENABLED: true
        CCD_MULTIPARTY_LOG_LEVEL: DEBUG
        CCD_MULTIPARTY_CASE_TYPES: CIVIL
        CCD_MULTIPARTY_EVENTS: DEFENDANT_RESPONSE,ACKNOWLEDGE_CLAIM,CLAIMANT_RESPONSE,queryManagementRaiseQuery,queryManagementRespondQuery
        ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-aat.service.core-compute-aat.internal
      secrets:
        DATA_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: true
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}

  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      devcpuRequests: 500m
      devmemoryRequests: 512Mi
      devcpuLimits: 2
      devmemoryLimits: 1Gi
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_DB_OPTIONS: "?stringtype=unspecified"
        DEFINITION_STORE_DB_PASSWORD: ${CCD_DEFINITION_STORE_POSTGRES_PASSWORD}
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        DEFINITION_STORE_TX_TIMEOUT_DEFAULT: 60
        WELSH_TRANSLATION_ENABLED: false
      secrets:
        DEFINITION_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: true
      keyVaults: []
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
