java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  readinessDelay: 45
  keyVaults:
    em-hrs-api:
      secrets:
        - name: storage-account-primary-connection-string
          alias: STORAGEACCOUNT_PRIMARY_CONNECTION_STRING
        - name: idam-system-user-name
          alias: HRS_SYSTEM_USER
        - name: idam-system-user-password
          alias: HRS_SYSTEM_USER_PASSWORD
        - name: microservicekey-em-hrs-api
          alias: S2S_KEY
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/javadatabase?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
    ENABLE_DB_MIGRATE: true
    RUN_DB_MIGRATION_ON_STARTUP: true
    CVP_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=$(BLOB_ACCOUNT_NAME);AccountKey=$(BLOB_ACCESS_KEY);EndpointSuffix=core.windows.net"
  postgresql:
    enabled: true
    auth:
      username: emhrs
      password: emhrs
blobstorage:
  enabled: true
  resourceGroup: em-hrs-api-aks
  teamName: "EM"
  location: uksouth
  setup:
    containers:
      - em-hrs-api

