version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.serenity-bdd:serenity-rest-assured
    versions:
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.liquibase:liquibase-core
    versions:
    - 4.3.0
    - 4.3.3
    - 4.3.4
  - dependency-name: org.pitest:pitest
    versions:
    - 1.6.5
  - dependency-name: uk.gov.service.notify:notifications-java-client
    versions:
    - 3.17.2-RELEASE
  - dependency-name: org.springframework.cloud:spring-cloud-starter-netflix-hystrix
    versions:
    - 2.2.8.RELEASE
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.3
  - dependency-name: org.testcontainers:junit-jupiter
    versions:
    - 1.15.3
  - dependency-name: org.liquibase.ext:liquibase-hibernate5
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-oauth2-resource-server
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-oauth2-jose
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-oauth2-core
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-oauth2-client
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-crypto
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-core
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: au.com.dius.pact
    versions:
    - 4.2.3
    - 4.2.4
  - dependency-name: io.netty:netty-handler-proxy
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-socks
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-unix-common
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-kqueue
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-epoll
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http2
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-resolver
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.60.Final
    - 4.1.62.Final
    - 4.1.63.Final
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - 1.7.1
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.1
  - dependency-name: uk.gov.hmcts.reform:idam-client
    versions:
    - 2.0.0
  - dependency-name: uk.gov.hmcts.reform:core-case-data-store-client
    versions:
    - 4.7.6
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: uk.gov.hmcts.java
    versions:
    - 0.12.4
    - 0.12.5
    - 0.12.6
  - dependency-name: com.azure:azure-storage-blob
    versions:
    - 12.10.1
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: uk.gov.hmcts.reform:service-auth-provider-client
    versions:
    - 4.0.0
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.2
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.28.Final
