---
spring:
  main:
    allow-bean-definition-overriding: true
    debug: false
  autoconfigure:
    debug: false
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5062/o}
        registration:
          oidc:
            client-id: webshow #TODO: create proper idam client-id for hrs
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO

test:
  url: ${TEST_URL:http://localhost:8081}

idam:
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:5062}
  client:
    id: ${OAUTH_CLIENT_ID:webshow}
    secret: ${IDAM_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_REDIRECT_URI:http://localhost:8081/oauth2/callback}
    grant_type: 'password'
    scope: 'openid roles profile'
  hrs-ingestor:
    user-name: ${IDAM_HRS_INGESTOR_SYSTEM_USER_NAME:AAAAAAAAAAAAAAAA}
    password:  ${IDAM_HRS_INGESTOR_SYSTEM_PASSWORD:AAAAAAAAAAAAAAAA}
s2s:
  api:
    url: ${S2S_BASE_URI:http://localhost:8489}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    serviceName: ${S2S_SERVICE_NAME:em_gw}
    ccdGwSecret: ${FUNCTIONAL_TEST_CCD_GW_SERVICE_SECRET:AAAAAAAAAAAAAAAA}
    ccdGwServiceName: ${CCD_GW_SERVICE_NAME:ccd_gw}

ccd-def:
  file: ${CCD_DEFINITION_FILE:CCD_HRS_v1.3-AAT.xslx}
  api:
    url: ${CCD_DEF_API:http://localhost:4451}

document_management:
  url: ${DM_STORE_APP_URL:http://localhost:4603}
  docker_url: http://dm-store:8080

core_case_data:
  api:
    url: ${CCD_DATA_API_URL:http://localhost:4452}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}
  storage:
    cvp:
      container-url: ${CVP_STORAGE_URL:http://localhost:10000/devstoreaccount1/cvptestcontainer/}
      connection-string: ${CVP_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
      blob-container-reference: ${CVP_STORAGE_CONTAINER_NAME:cvptestcontainer}
    vh:
      container-url: ${VH_STORAGE_URL:http://localhost:10000/devstoreaccount1/vhtestcontainer/}
      connection-string: ${VH_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
      blob-container-name: ${VH_STORAGE_CONTAINER_NAME:vhtestcontainer}
    hrs:
      connection-string: ${HRS_STORAGEACCOUNT_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
      cvp-dest-blob-container-name: ${HRS_CVP_DEST_CONTAINER_NAME:emhrstestcontainer}
      vh-dest-blob-container-name: ${HRS_VH_DEST_CONTAINER_NAME:emhrsvhtestcontainer}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on


close-ccd-test-cases: ${CLOSE_CCD_TEST_CASES:false}
upload-cdd-definition: ${UPLOAD_CCD_DEF:false}
ttl:
  default-ttl: ${DEFAULT_TTL:P7Y}
  enabled: ${TTL_ENABLED:true}
