---
version: '3'

services:
  em-hrs-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emhrs
      - POSTGRES_USER=emhrs
      - POSTGRES_PASSWORD=emhrs
    ports:
      - 5432:5432

  azure-storage-emulator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    command: "azurite-blob --blobHost 0.0.0.0 --loose"
    volumes:
      - em-hrs-docker-azure-blob-data:/opt/azurite/folder

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_EM_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_EM_HRS_API: AAAAAAAAAAAAAAAA
      TESTING_SUPPORT_ENABLED: "true"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx512m -XX:MaxPermSize=512m

  idam-api:
    image: hmctspublic.azurecr.io/hmcts/rse/rse-idam-simulator:latest
    environment:
      # these environment variables are used by java-logging library
      ROOT_APPENDER:
      JSON_CONSOLE_PRETTY_PRINT:
      ROOT_LOGGING_LEVEL:
      REFORM_SERVICE_TYPE:
      REFORM_SERVICE_NAME:
      REFORM_TEAM:
      REFORM_ENVIRONMENT:
      LOGBACK_DATE_FORMAT:
      LOGBACK_REQUIRE_THREAD:
      LOGBACK_REQUIRE_ALERT_LEVEL: "false"
      LOGBACK_REQUIRE_ERROR_CODE: "false"
      SERVER_PORT: 5000
      SIMULATOR_OPENID_BASE_URL: http://localhost:5000
    ports:
      - 5000:5000

volumes:
  pacts:
  em-hrs-docker-azure-blob-data:
