management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Hearing Recordings Service

  jpa:
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true
  main:
    allow-bean-definition-overriding: true

  liquibase:
    enabled: ${ENABLE_DB_MIGRATE:false}
    change-log: classpath:/db/db.changelog-master.xml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emhrs}
    username: ${SPRING_DATASOURCE_USERNAME:emhrs}
    password: ${SPRING_DATASOURCE_PASSWORD:emhrs}

  jackson:
    property-naming-strategy: KEBAB_CASE

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5000/o}
        registration:
          oidc:
            client-id: microservicekey-em-hrs-api
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

auth:
  idam:
    client:
      baseUrl: ${IDAM_API_BASE_URI:http://localhost:5000}
  provider:
    service:
      client:
        baseUrl: ${S2S_BASE_URI:http://localhost:4502}

# service-auth-provider-client lib
idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
    microservice: ${S2S_SERVICE_NAME:em_hrs_api}
  s2s-authorised:
    services: ${S2S_NAMES_WHITELIST:jui_webapp,em_ccd_orchestrator,em_gw}
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:5000}
    client:
      id: microservicekey-em-hrs-api
      secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
      redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}
      grant_type: 'password'
      scope: 'openid roles profile'

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d04b52b1-20e5-473a-8ac4-3f6859ea113c}
  storage:
    hrs:
      connection-string: ${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
      blob-container-reference: ${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:emhrstestcontainer}
    cvp:
      connection-string: ${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
      blob-container-reference: ${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:cvptestcontainer}

#Below values are examples and needs to updated with correct values
notify:
  apiKey: ${NOTIFICATION_API_KEY:test_key-86d79f79-5045-4df2-87d1-6b7d87b41f6b-a703ea6c-9869-42a7-aaa8-38c98a0cc044}
  emailTemplateId: 58f6384c-64f9-4ddc-a409-259fe04d1836

# OpenId Connect
oidc:
  issuer: ${OIDC_ISSUER_BASE_URI:http://localhost:8080/openam/oauth2/hmcts}
