---
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: webshow #TODO: create proper idam client-id for hrs
            client-secret: ${S2S_KEY:Z4J6PEQ4L34JLQNV}

test:
  url: ${TEST_URL:http://em-hrs-api-aat.service.core-compute-aat.internal}

idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  api:
    url: ${IDAM_API_BASE_URI:https://idam-api.aat.platform.hmcts.net}
  client:
    id: ${OAUTH_CLIENT_ID:webshow}
    secret: ${IDAM_CLIENT_OAUTH_SECRET:QfnbQkh2cvROJDe9tFE3WNfD4a0Q2w8Q}
    redirect_uri: ${IDAM_REDIRECT_URI:https://em-hrs-api-aat.service.core-compute-aat.internal/oauth2/callback}
    grant_type: 'password'
    scope: 'openid roles profile'

s2s:
  api:
    url: ${S2S_BASE_URI:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:ZTUJMGDXR4ATXB4O}
    serviceName: ${S2S_SERVICE_NAME:em_gw}
    ccdGwSecret: ${FUNCTIONAL_TEST_CCD_GW_SERVICE_SECRET:2SL33JSNZF3IAO7I}
    ccdGwServiceName: ${CCD_GW_SERVICE_NAME:ccd_gw}

ccd-def:
  file: ${CCD_DEFINITION_FILE:hrs_ccd_case_definition_AAT.xlsx}
  api:
    url: ${CCD_DEF_API:http://ccd-definition-store-api-aat.service.core-compute-aat.internal}

document_management:
  url: ${DM_STORE_APP_URL:http://dm-store-aat.service.core-compute-aat.internal}
  docker_url: http://dm-store:8080

core_case_data:
  api:
    url: ${CCD_DATA_API_URL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d30268e8-8979-4579-8d58-010dbe03a1e6}
  storage:
    cvp:
      container-url: ${CVP_CONTAINER_URL:https://emhrsapiaat.blob.core.windows.net/recordings/}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on
---
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: webshow #TODO: create proper idam client-id for hrs
            client-secret: ${S2S_KEY:Z4J6PEQ4L34JLQNV}

test:
  url: ${TEST_URL:http://em-hrs-api-aat.service.core-compute-aat.internal}

idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  api:
    url: ${IDAM_API_BASE_URI:https://idam-api.aat.platform.hmcts.net}
  client:
    id: ${OAUTH_CLIENT_ID:webshow}
    secret: ${IDAM_CLIENT_OAUTH_SECRET:QfnbQkh2cvROJDe9tFE3WNfD4a0Q2w8Q}
    redirect_uri: ${IDAM_REDIRECT_URI:https://em-hrs-api-aat.service.core-compute-aat.internal/oauth2/callback}
    grant_type: 'password'
    scope: 'openid roles profile'

s2s:
  api:
    url: ${S2S_BASE_URI:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:ZTUJMGDXR4ATXB4O}
    serviceName: ${S2S_SERVICE_NAME:em_gw}
    ccdGwSecret: ${FUNCTIONAL_TEST_CCD_GW_SERVICE_SECRET:2SL33JSNZF3IAO7I}
    ccdGwServiceName: ${CCD_GW_SERVICE_NAME:ccd_gw}

ccd-def:
  file: ${CCD_DEFINITION_FILE:hrs_ccd_case_definition_AAT.xlsx}
  api:
    url: ${CCD_DEF_API:http://ccd-definition-store-api-aat.service.core-compute-aat.internal}

document_management:
  url: ${DM_STORE_APP_URL:http://dm-store-aat.service.core-compute-aat.internal}
  docker_url: http://dm-store:8080

core_case_data:
  api:
    url: ${CCD_DATA_API_URL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d30268e8-8979-4579-8d58-010dbe03a1e6}
  storage:
    cvp:
      container-url: ${CVP_CONTAINER_URL:https://emhrsapiaat.blob.core.windows.net/recordings/}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on
